[package]
name = "rustop"
version = "0.4.1"
authors = ["wojciechkepka <wojtek.kepka@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "2.31.2"
colored = "1.8"
glob = "0.3.0"