[package]
name = "rustop"
version = "0.2.0"
authors = ["wojciechkepka <wojtek.kepka@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"